#!/bin/bash

wget --no-check-certificate -O - -q https://$1/robots.txt | grep -i "^Disallow: /$">/tmp/debug.log
SUCCESS=$?

# if [ "$COUNT" -gt 5 ]; then
if [ "$SUCCESS" == 1 ]; then
    echo "Good robots: ^Disallow: /\$ not found."
    exit 0;
fi

echo "Bad robots: ^Disallow: /\$ found.";
exit 2;

