- hosts: localhost
#
#  vars:
#    apache_group:
#      Debian: "root"
#      RedHat: "apache"
#    apache_ctl:
#      Debian: "/usr/sbin/apache2ctl"
#      RedHat: "/usr/sbin/apachectl"
#
  tasks:
      #- name: Update apt
      #become: yes
      #apt: update_cache=yes cache_valid_time=3600

    - name: Install nagios
      become: yes
      apt: pkg={{ item }} state=latest
      with_items:
      - ssh
      - git
      - sudo
      - nagios3
      - nagios-plugins
      - nagios-nrpe-server
      - python-passlib
      - python-requests

    - name: Ensure .ssh folder for nagios user
      file: path=/var/lib/nagios/.ssh state=directory owner=nagios group=nagios mode=0700 recurse=yes
      become: yes

    - name: Clean out dist nagios config
      file: path=/etc/nagios3 state=absent
      become: yes

    - name: Clean out dist nagios-plugins config
      file: path=/etc/nagios-plugins state=absent
      become: yes

    - name: Clean out dist nagios-extras config
      file: path=/usr/local/share/nagios-extras state=absent
      become: yes

    - name: Add out nagios config
      synchronize: src=nagios3 dest=/etc/
      become: yes

    - name: Add out nagios-plugins config
      synchronize: src=nagios-plugins dest=/etc/
      become: yes

    - name: Add out nagios-extras config
      synchronize: src=nagios-extras dest=/usr/local/share/
      become: yes

    - name: Set nagios user
      htpasswd: path=/etc/nagios3/htpasswd.users name=neontribe password="{{ neontribe_pass }}" crypt_scheme=md5_crypt
      become: yes

    - name: Copy in the ssh rsa private key
      copy: src=ssh/id_rsa dest=/var/lib/nagios/.ssh/id_rsa owner=nagios group=nagios mode=0700
      become: yes

    - name: Strip the passphrase off the ssh key
      shell: ssh-keygen -p -P {{ sshkey_passwd }} -f /var/lib/nagios/.ssh/id_rsa
      become: yes

    - name: Copy in the ssh rsa public key
      copy: src=ssh/id_rsa.pub dest=/var/lib/nagios/.ssh/id_rsa.pub owner=nagios group=nagios mode=0700
      become: yes

    - name: Copy in the ssh known hosts
      copy: src=ssh/known_hosts dest=/var/lib/nagios/.ssh/known_hosts owner=nagios group=nagios mode=0600
      become: yes
